### ISSUE TITLE
Error running the bot

### ISSUE THREAD

**Issue by sarmel** [vladthelittleone/arbitrage.js#8]
I get this error when running the bot.
error [arbitrage/index.js] Try fetch balances but gets: hitbtc GET http://api.hitbtc.com/api/1/public/symbols request timed out (10000 ms)

**Comment by vladthelittleone** [comment]
@sarmel, hi. All exchanges has rate limits.
see: https://api.hitbtc.com/#rate-limiting

**Comment by sarmel** [comment]
fix the problem by upgrading ccxt package

**Comment by sarmel** [comment]
how to solve this problem?
